### ISSUE TITLE
Please use latest version of com.sun.jna and com.sun.jna.platform

### ISSUE THREAD

**Issue by merks** [eclipse-passage/passage#1084]
I've been working on a view that highlights duplicate versions in the release train repository.  This view also boils down the requirement information to those requirements that resolve only one particular version of the installable unit, i.e., that 'lock in" a specific version.

Here we see that Passage is the only thing that requires the older version of com.sun.jna*:

![image](https://user-images.githubusercontent.com/208716/169522168-2db0ab85-85d2-47f4-bd38-9ab0ebdc250e.png)

You would need to modify the *.target:
```
			<unit id="com.sun.jna" version="5.8.0.v20210503-0343"/>
			<unit id="com.sun.jna.platform" version="5.8.0.v20210406-1004"/>
```
And change the version ranges to allow for 5.8.

Unfortunately a newer version of com.github.oshi.oshi-core that allows com.sun.jna* 5.8 to be used would be needed as well.

@jonahgraham 

Is this just a matter of increasing the 4.5.1 to 5.8.0 in the bundle recipe?

![image](https://user-images.githubusercontent.com/208716/169523933-92aec2eb-b0b7-435d-ac58-a04bb811c3b9.png)

Note that I created a setup for Orbit to make contribution easier:

![image](https://user-images.githubusercontent.com/208716/169524468-0ac66ccb-aa11-48a6-a8b3-d739e9baa70c.png)

**Comment by jonahgraham** [comment]
> Unfortunately a newer version of com.github.oshi.oshi-core that allows com.sun.jna* 5.8 to be used would be needed as well.
>
> @jonahgraham
>
> Is this just a matter of increasing the 4.5.1 to 5.8.0 in the bundle recipe?


It could be, if all the uses of JNA in OSHI are reviewed. But I would be hesitant to do that based on this [comment](https://github.com/oshi/oshi/blame/master/oshi-core/pom.xml#L18) in OSHI's pom.xml (introduced fixing previous JNA issues in https://github.com/oshi/oshi/issues/1040):

```xml
<!-- Due to critical nature of OSHI jna usage, set to dependency management to help influence usage -->
```

There are many new versions of OSHI, so I would encourage upgrading rather than playing around with dependency versions.

**Comment by ruspl-afed** [comment]
Thank you @merks for submitting this issue, 
And thank you @jonahgraham for commenting
The situation with different versions of JNA is known. However, the version of OSHi that Passage uses now works fine for our scenarios. I need to mention that Passage uses JNA a bit more intensive than Platform does, since we need to support things like license on removeable drives and so on. 
Switching for any newer version of OSHi will require testing effort from our side and I would like to understand better the nearsest plans regarding recommended JNA version to be used by SimRel before selecting new OSHi release.
I kindly ask you to share with me your thoughts on this.

**Comment by merks** [comment]
There appear to be many versions of com.sun.jna in Orbit

![image](https://user-images.githubusercontent.com/208716/169639197-6fdc02f8-4522-45d9-9d7f-f120812ed9d2.png)

But on the 2022-06 release train, there are only two and the other projects, Eclipse, CDT, EGit and Apache http 5, are using the 5.8 version.  Ideally Passage would also use the 5.8 version.

But I understand that time needs to be invested to get a new version of OSHi and to test it that that his might not be your project's highest priority.  Migrating to a new version would be very nice, but it is not a show stopper or nor urgent.

**Comment by ruspl-afed** [comment]
Switched to JNA 5.12.1 that is aligned with Eclipse Platform 2022-12, see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L175
