### ISSUE TITLE
FLS needs user interaction on startup - cannot be used as system daemon

### ISSUE THREAD

**Issue by jensgw** [eclipse-passage/passage#1100]
Hi there, 

currently the floating license server requires user interaction to fully start up, i.e. press  "p" to start the server.
This makes it impossible to use the fls as system daemon that automatically starts with your server computer.

It is unlikely and undesirable in any deployment scenario to require a human to interact with the server startup.
Why require user interaction here when it is not needed?

Compare to a webserver, a file server, any other server. Some of them have debug or interactive modes, but those are not the default.
Therefore, I suggest changing the startup behavior to always assume  "p", and add a new command line parameter, e.g. -interactive
that then shows the menu at startup.

Best regards
Jens

**Comment by eparovyshnaya** [comment]
@jensgw  thank you for your interest. 

FLS has not been designed as a deamonable server mostly because it intended to have wide interaction with admin, for exmple
 - to deploy a product license under the server
 - to perform diagnnostic monitoring during the server operation, etc

Meaning FLS needs interaction not only on startup.

So it's not the matter of one more cli-option invention. If we desire to have a deamon (background) mode, we demand operating without terminal (without interaction).  

Having this described, I would rather state the feature proposal as _Redesign FLS to support deamon launch_ . 

@jensgw, can it be that you doesn't actually want FLS to be a deamon, but more of a silent foreground application? Like it can still be the owner of a terminal to talk to admin, but does not demand attention if can proceed without it?

**Comment by jensgw** [comment]
Yes, agreed on the "Redesign FLS to support deamon launch".

Currently we do some testing with passage and FLS and see if it fits in our infrastructure. Immediately apparent was that the server component does not behave as a typical server would.

We would very much like a daemon mode, no console no terminal, if there are issues there is a log file the server can write to.

Requiring user interaction binds human resources, no server does that. That begs the question, why does passage behave differently? Assuming correct setup: a server should start up and begin operations and should never require any form of user interaction, problems are logged in a log file. There can be a debug mode where the server runs in foreground and logs are also displayed on the console. Compare to apache2, freeradius, etc. basically everything that calls itself server.

In general, if user interaction is needed it should be split out in a separate component, e.g. floating license server and floating license server control client. The later can be a client that connects to the server and can send commands.

Have the fls running on a remote machine, for some reason that needs to reboot, and now all users have to wait for an admin to press p before they can get licenses. Depending on how many admins a company has, that might take a minute, or days ...
Additionally a server that needs user input does not scale. Imagine a  large deployment of fls to lets say 38473 servers in a cloud environment. Those servers do not operate unless every one of them got the keypress p.
