### ISSUE TITLE
Support requirement for multiple values in Hardware evaluation expression

### ISSUE THREAD

**Issue by HannesWell** [eclipse-passage/passage#1122]
For hardware elements that can have multiple instances on a usual computer, like Network-Adapters or drives, one sometimes wants to ensure that that multiple instances with certain properties are present and/or that only a fixed set of instances (and not more) with certain properties is present.
In those cases it would be useful to enhance hardware expression evaluation to support the following:

- Parse multiple values for the same expression key and evaluate each value. This is PR #1115.
With that it would be possible to define an expression like `hwdisk.serial=123;hwdisk.serial=456`, which then requires the computer to have at least one disk with serial `123` and one disk with serial `456`.
- Add means to specify that there must not be more respectively that there are only exactly those elements (network-adapters, drives) than those that are specified in the expression.
So if one defines an expression `hwdisk.serial=123;hwdisk.serial=456` (and something to enable the 'no-more'-mode) then the execution computer must have exactly one drive with serial `123` and one drive with serial `456` and no more.

Either the Berlin protocol could be enhanced or this could be implemented in an own protocol. In general I think this could be interesting for others as well and therefore wanted to propose that as change within Passage instead of just implementing a custom protocol.

**Comment by eparovyshnaya** [comment]
Dear @HannesWell, thank you very much for you interest in these deep levels of condition assessment. 

Must say, Berlin protocol is simple by design and must stay this way. It found wide use in production and proved to be sufficient as it is. 

Passage API offers full set of condition assessment interfaces and the way to contribute them to the runtime of Passage core. These are your means, that we desigend for cases like this, intended to be used for the purposes of extension. 

I must emphsize, this is very much important point: Passage architecture offers huge lots of extensions exactly for the cases as yours. We discourage modifications in the favour of extensions, as having API this rich is a burden on our resources, taken deliberately, as we built Passage on best design practices, including _open for extension / closed for modification_ principle.  

In case you think your new idea of assessment could be interesting for others, I would recommend you to use supplied interfaces to implement your own library. It can reside, for example, on maven. Thus it could be used by any interested party for any product, protected by Passage. 

Feel free to post an issue here in case you find something impossible to implement or plug with the current state of API .
