### ISSUE TITLE
FLS: evolve to reduce maintenance cost

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1404]
Eclipse Passage Floating License Server was created as a demo product to illustrate feasibility of floaing license support by Passage Runtime. FLS is not a part of SimRel and does not affect design or functionality of Passage Runtime Core libraries.

In the current state of soucebse FLS functionality appears to be attractive for reuse despite it was not designed in a reusable way and is not going to evlove that way. 

Both reuse demands and by-release support evoke pressure on Eclipse Passage project resources, which are scarce as they are.

Scope of this epic-task is to take measures to reduce FLS maintenance cost.

**Comment by eparovyshnaya** [comment]
FLS sample product shut down.

**Comment by iils-hwellmann** [comment]
> FLS sample product shut down.

This is a decision we don't appreciate, but nevertheless respect. Because we consider the FLS still a relevant part of Passage and as I have contributed to its maintenance in the past (with my private account @HannesWell, that is registered with my EF-account, which this company account isn't), we have decide to take over the work and continue the maintenance of the parts required for the FLS that are now gone in a reduced fork:
- https://github.com/iils-mbh/eclipse.passage.fls

We intend to align the fork to each passage release and develop it further on a best effort basis and on our own discretion. Still, contributions from anybody are welcome and we hope that the FLS will make its way back to the Passage Eclipse-project one day.
